package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setSize(1920, 1050);
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.WHITE);

        Component[] components = pnlButtons.getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                JButton button = (JButton) component;
                button.setBackground(new Color(251, 219, 190));
                button.setContentAreaFilled(false);
                button.setOpaque(true);
                
                if(button.getText().equals("Tracker")){
                    button.setBackground(new Color(244, 159, 83));
                }

                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Component[] components = pnlButtons.getComponents();
                        for (Component component : components) {
                            if (component instanceof JButton) {
                                JButton button = (JButton) component;
                                button.setBackground(new Color(251, 219, 190));
//                                button.setContentAreaFilled(false);
//                                button.setOpaque(true);
                            }
                        }

                        button.setBackground(new Color(244, 159, 83));
//                        button.setContentAreaFilled(false);
//                        button.setOpaque(true);
                    }
                });

            }
        }

        setPanelsVisibilityFalse();
        pnlUi.add(PnlTracker.getInstance());
        PnlTracker.getInstance().repaint();
        PnlTracker.getInstance().revalidate();
        PnlTracker.getInstance().setVisible(true);
    }

    private void setPanelsVisibilityFalse() {
        PnlTracker.getInstance().setVisible(false);
        PnlMore.getInstance().setVisible(false);
        PnlReport.getInstance().setVisible(false);
        PnlActivity.getInstance().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnTracker = new javax.swing.JButton();
        btnMore = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnActivity = new javax.swing.JButton();
        pnlUi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time Tracker");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 70);

        pnlButtons.setBackground(new java.awt.Color(255, 255, 255));
        pnlButtons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlButtons.setLayout(null);

        btnTracker.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTracker.setText("Tracker");
        btnTracker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackerActionPerformed(evt);
            }
        });
        pnlButtons.add(btnTracker);
        btnTracker.setBounds(110, 10, 200, 50);

        btnMore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnMore.setText("More");
        btnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreActionPerformed(evt);
            }
        });
        pnlButtons.add(btnMore);
        btnMore.setBounds(1580, 10, 200, 50);

        btnReport.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        pnlButtons.add(btnReport);
        btnReport.setBounds(590, 10, 200, 50);

        btnActivity.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnActivity.setText("Activity");
        btnActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivityActionPerformed(evt);
            }
        });
        pnlButtons.add(btnActivity);
        btnActivity.setBounds(1080, 10, 200, 50);

        getContentPane().add(pnlButtons);
        pnlButtons.setBounds(10, 70, 1900, 70);

        pnlUi.setBackground(new java.awt.Color(255, 255, 255));
        pnlUi.setLayout(null);
        getContentPane().add(pnlUi);
        pnlUi.setBounds(-1, 168, 1920, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackerActionPerformed
        setPanelsVisibilityFalse();
        pnlUi.add(PnlTracker.getInstance());
        PnlTracker.getInstance().repaint();
        PnlTracker.getInstance().revalidate();
        PnlTracker.getInstance().setVisible(true);
    }//GEN-LAST:event_btnTrackerActionPerformed

    private void btnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreActionPerformed
        setPanelsVisibilityFalse();
        pnlUi.add(PnlMore.getInstance());
        PnlMore.getInstance().repaint();
        PnlMore.getInstance().revalidate();
        PnlMore.getInstance().setVisible(true);
    }//GEN-LAST:event_btnMoreActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        setPanelsVisibilityFalse();
        pnlUi.add(PnlReport.getInstance());
        PnlReport.getInstance().repaint();
        PnlReport.getInstance().revalidate();
        PnlReport.getInstance().setVisible(true);
        PnlReport.getInstance().createChart();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivityActionPerformed
        setPanelsVisibilityFalse();
        pnlUi.add(PnlActivity.getInstance());
        PnlActivity.getInstance().repaint();
        PnlActivity.getInstance().revalidate();
        PnlActivity.getInstance().setVisible(true);
    }//GEN-LAST:event_btnActivityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivity;
    private javax.swing.JButton btnMore;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTracker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlUi;
    // End of variables declaration//GEN-END:variables
}
